version: '3'

services:
  lavalink:
    image: fredboat/lavalink:8ebaba1
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333"
      - "2333:2333/udp"
    volumes:
      - ./Lavalink/configuration.yml:/opt/Lavalink/application.yml
