version: '3'

services:
  lavalink:
    image: fredboat/lavalink:4782f1f
    container_name: lavalink
    restart: always
    ports:
      - "2333:2333"
      - "2333:2333/udp"
    volumes:
      - ./Resources/application.yml:/opt/Lavalink/application.yml
